500 Internal Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/root/dev/proj/b2cache/app.py", line 31, in default
    return await views.default_3(request)
  File "/root/dev/proj/b2cache/views.py", line 216, in default_3
    return await fetch_remove_by_chunk(request, bkey, response_headers, http_range_str)
  File "/root/dev/proj/b2cache/views.py", line 167, in fetch_remove_by_chunk
    resp, databuffer = await b2utilsx.get_data_by_chunk(request, bkey, response_headers, http_range_str)
  File "/root/dev/proj/b2cache/b2utilsx.py", line 108, in get_data_by_chunk
    async with session.get(url, headers=headers, verify_ssl=False) as resp:
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
